Started implementing support for composite primary keys, fixed file structure
IU-Softwareengineering/KMI_System pull request #11
Opened 2024-06-05 10:08 UTC by M0ttii

- Fixed file structure 
- Added CompositeKey Annotation
- Added composite key methods to BaseQuery

2024-06-05 15:13 UTC, justincepik requested changes
looks good, aber genau wie bei dem anderen PR, wäre es noch gut einen kleinen test case hinzuzufügen

EDIT: achso und bitte rebasen

2024-06-05 18:51 UTC, h0rzn approved these changes

2024-06-05 18:53 UTC, M0ttii commented
> looks good, aber genau wie bei dem anderen PR, wäre es noch gut einen kleinen test case hinzuzufügen
> 
> EDIT: achso und bitte rebasen

tests mach ich wann anders, heut keine Zeit leider

2024-06-06 10:37 UTC, justincepik approved these changes

2024-06-06 12:50 UTC, merged