added save option to  DebitorGUI
IU-Softwareengineering/KMI_System pull request #24
Opened 2024-06-14 09:41 UTC by JayTie23

2024-06-17 11:20 UTC, M0ttii approved these changes
Sieht gut aus, nur dein adresse-attribut war ein string. Das muss allerdings ein Adresse Entity sein -> hab also fix den Typen von String zu Adresse geändert.

2024-06-17 17:30 UTC, M0ttii requested changes
Debitor muss mit AdresseEntity erstellt werden, nicht mit adresse_nr als string -> im code kommentiert

2024-06-17 17:30 UTC, M0ttii commented on src/main/java/com/iu/kmi/layout/DebitorInterface.java
> +        Debitor debitor = new Debitor(jTextField1.getText(), jTextField3.getText(), jTextField2.getText(), jTextField6.getText(), jTextField4.getText(), jTextField5.getText());
Da Debitor nun das AdresseEntity und nicht die adresse_nr als Parameter annimmt muss hier auch ein AdresseEntity eingetragen werden

2024-06-18 15:43 UTC, JayTie23 commented
Die Adressen Klasse muss zunächst angepasst werden, um schauen zu können, ob alles soweit, funktioniert.

2024-06-18 19:27 UTC, M0ttii approved these changes

2024-06-18 19:29 UTC, h0rzn commented
Das Adresse-Repository fehlt noch allerdings ist das Program derzeit sowieso nicht lauffähig. Ich merge mit Bitte um schnellen Follow-Up @othman3mm

2024-06-18 19:29 UTC, merged

2024-06-18 20:06 UTC, othman3mm commented
> Das Adresse-Repository fehlt noch allerdings ist das Program derzeit sowieso nicht lauffähig. Ich merge mit Bitte um schnellen Follow-Up @othman3mm

Ich habe die Adresse-klasse schon gemacht.

Kannst du bitte mir sagen, was ist das Problem? @h0rzn