Kondition speichern
IU-Softwareengineering/KMI_System pull request #25
Opened 2024-06-14 10:04 UTC by RainerStoff69

added save function and repository for Kondition

2024-06-17 11:23 UTC, M0ttii requested changes
Hab kommentiert, beim repository falschen typen benutzt

2024-06-17 11:23 UTC, M0ttii commented on src/main/java/com/iu/kmi/repositories/KonditionRepository.java
> +public interface KonditionRepository extends Repository<Kondition, Integer>{
Falscher Typ, muss Repository<Kondition, String> sein

2024-06-17 18:00 UTC, h0rzn commented
Konflikte lösen

2024-06-18 11:54 UTC, M0ttii approved these changes

2024-06-18 15:56 UTC, merged