Auftrag erstellen implementiert
IU-Softwareengineering/KMI_System pull request #28
Opened 2024-06-17 15:47 UTC by dl25dev

2024-06-17 16:07 UTC, justincepik approved these changes

2024-06-17 18:00 UTC, h0rzn commented
Konflikt lösen

2024-06-18 11:48 UTC, M0ttii requested changes

2024-06-18 11:48 UTC, M0ttii commented on src/main/java/com/iu/kmi/database/repository/AuftragRepository.java
> +package com.iu.kmi.database.repository;
Falsches package -> gehört in com.iu.kmi.repository oder com.iu.kmi.repositories

2024-06-18 11:48 UTC, M0ttii commented on src/main/java/com/iu/kmi/entities/Auftrag.java
>      private String angebotNr;
Falscher Typ

2024-07-04 19:42 UTC, h0rzn commented
veraltet

2024-07-04 19:42 UTC, closed without merging