Adding condition class
IU-Softwareengineering/KMI_System pull request #3
Opened 2024-05-29 12:22 UTC by JayTie23

Created ConditionEntity class with constructor, getter and setter

2024-06-03 10:50 UTC, justincepik requested changes
Sieht gut aus, wenn du kannst mach bitte noch einen JUnit Test rein, am besten abwarten bis die 'BDK-Angebot' branch gemerged wurde, dann kannst du einfach einen Test dazu schreiben

2024-06-03 15:23 UTC, AnastaciaBe requested changes
Schließe mich da an und es müsste noch die id geändert werden. Umbenennen und als String statt int (laut Dozent)

2024-06-06 12:52 UTC, h0rzn commented
Änderungen an der Ordner-Struktur https://github.com/IU-Softwareengineering/KMI_System/pull/11

2024-06-06 15:13 UTC, h0rzn commented
Sieht so aus als hättest du gerebased. Stimmt das?

2024-06-06 15:57 UTC, closed without merging