Fix Kunden Klasse && UnitTest-Kunde
IU-Softwareengineering/KMI_System pull request #31
Opened 2024-06-17 19:54 UTC by othman3mm

Fix Kunden Klasse && UnitTest-Kunde

2024-06-18 07:47 UTC, M0ttii requested changes

2024-06-18 07:47 UTC, M0ttii commented on src/main/java/com/iu/kmi/entities/Kunde.java
>      private Adresse adresse;
@JoinColumn annotation fehlt

2024-06-19 19:39 UTC, h0rzn commented
Kannst du bitte auch gleich den nbproject-Ordner in / entfernen?

2024-06-20 07:43 UTC, othman3mm commented
> Kannst du bitte auch gleich den nbproject-Ordner in / entfernen?

done

2024-07-04 19:39 UTC, h0rzn commented
done via https://github.com/IU-Softwareengineering/KMI_System/pull/50/

2024-07-04 19:39 UTC, closed without merging