Update Kundenanfrage
IU-Softwareengineering/KMI_System pull request #33
Opened 2024-06-18 10:15 UTC by Lennyad

Update Kundenanfrage/Kundenanfrage Test,
Kunden Klasse momentan unvollständig daher laufen Tests nicht durch, trzdm bitte auch nochmal checken obs sonst funktioniert

2024-06-19 10:49 UTC, M0ttii requested changes

2024-06-19 10:49 UTC, M0ttii commented on src/main/java/com/iu/kmi/entities/Kundenanfrage.java
> +    @Column(name = "kundenanfrage_nr")
@Id

2024-06-19 10:49 UTC, M0ttii commented on src/main/java/com/iu/kmi/entities/Kundenanfrage.java
NoArgs Konstruktor fehlt

2024-07-04 19:38 UTC, h0rzn commented
done via https://github.com/IU-Softwareengineering/KMI_System/pull/50/

2024-07-04 19:38 UTC, closed without merging