Kundendaten Speichern
IU-Softwareengineering/KMI_System pull request #36
Opened 2024-06-18 16:13 UTC by Bludwell

AngebotTest korrigiert,
KundenRepository eingefügt,
Kunde klasse angepasst,
Eventhandler speichern hinzugefügt,
DatabaseConnection zum test.

2024-06-18 19:39 UTC, M0ttii requested changes

2024-06-18 19:39 UTC, M0ttii commented on src/main/java/com/iu/kmi/database/DatabaseConnection.java
> +    private static final String URL = "jdbc:mysql://159.69.241.119:3306/dev3_db";
pack pls in die gitignore

2024-06-18 19:39 UTC, M0ttii commented on src/main/java/com/iu/kmi/entities/Kunde.java
> +    @Id(name = "kundennr")
kunden_nr

2024-06-18 19:39 UTC, M0ttii commented on src/main/java/com/iu/kmi/entities/Kunde.java
>      private String geburtsdatum;
@Column fehlt

2024-06-18 19:39 UTC, M0ttii commented on src/main/java/com/iu/kmi/entities/Kunde.java
>      private Adresse adresse;
@Column fehlt

2024-06-18 19:39 UTC, M0ttii commented on src/main/java/com/iu/kmi/entities/Kunde.java
>      private String benutzername;
benutzername kommt nicht rein

2024-06-18 19:39 UTC, M0ttii commented on src/main/java/com/iu/kmi/entities/Kunde.java
>      private String benutzername;
password auch nich

2024-06-19 07:28 UTC, M0ttii commented
Generell ist die Frage wer den Kunden machen sollte. Ottman und du haben jetzt beide eine andere Kundenklasse gepusht

2024-06-19 08:26 UTC, Bludwell commented
Stimmt. Ich habe die halt verändert damit ich das Programm zum laufen bekomme. Und meine aufgabe war es ja kundendaten abspeichern zu ermöglichen. Die jdbc daten hab ich extra drin gelassen damit du den fehler testen kannst. Gern kann othman die kundenklasse machen, dann pass ich den rest heute abend noch an.

2024-06-21 07:41 UTC, h0rzn commented on src/main/java/com/iu/kmi/entities/Kunde.java
> +    @Id(name = "kundennr")
kunde_nr

2024-06-21 07:41 UTC, h0rzn commented on src/main/java/com/iu/kmi/entities/Kunde.java
>      private String geburtsdatum;
geburtsdatum raus

2024-06-21 07:42 UTC, h0rzn commented on src/main/java/com/iu/kmi/entities/Kunde.java
>      private Adresse adresse;
@JoinColumn mit adresse_nr

2024-07-04 19:40 UTC, h0rzn commented
already done

2024-07-04 19:40 UTC, closed without merging